### ISSUE TITLE
A very short tutorial how I am suppose to run this?

### ISSUE THREAD

**Issue by SM411** [jabbink/MSG2015-finder#1]
Hi!
I have not much experience with JS,and I have not completly grasped the concept of programming web-browsers, but I know basic programming, and I userstand what this script does.

I tried a lot of googling, and ended up with Node.js. I might have stepped in the wrong direction, so a short guide would help a lot!

**Comment by jabbink** [comment]
`git clone`
`npm install`
`npm start`

Watch console
