### ISSUE TITLE
doesn't work after got error message few times

### ISSUE THREAD

**Issue by agabob** [jabbink/MSG2015-finder#2]
I running this app about a hour. I added my account ID and joined few rooms for test purpose. It seems working perfectly.
But I got error: connect ETIMEDOUT message 10 or more times. And then the app can't tracking my account anymore.
I killed process and launch the app again. It works very well but I have same issue after I got ETIMEDOUT error 10 or more times.

**Comment by agabob** [comment]
1. Run
2. Check app is working
3. Disable network adapter
4. Got error message 50-60 times.
5. Enable network adapter
6. Cannot tracking anymore

**Comment by jabbink** [comment]
Thanks for letting me know. I am looking into it. My first guess would be that I accidentally skip an entire batch of users when an error occurs instead of rescheduling that one.

**Comment by jabbink** [comment]
Yep, that's it. Fix will be pushed before reset today.

**Comment by jabbink** [comment]
@InnerPeaceKR I think this is fixed in ea7cccf0537c15ac2f3cf46197f9ecc97feefdbc

I will close this when you can confirm this.

(don't start it with `node app` anymore; use `npm start` or `./bin/www` instead)

**Comment by agabob** [comment]
It works even if got some errors! Great!

**Comment by jabbink** [comment]
Thanks for confirming.

Closing
