### ISSUE TITLE
Refresh

### ISSUE THREAD

**Issue by kanyawest** [jabbink/MSG2015-finder#3]
I've got the script to work, looks pretty useful indeed

Just a question, does the script updates itself, I mean, I plan to keep it on until the game resets or do I have to run the script over again because it took quite some time for it to load and I might not be able to get into rooms

Thanks in advance

**Comment by jabbink** [comment]
It autoupdates. I just put a version of this online [here](http://msg15.abb.ink) so there is no need to run this locally.
